/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as RedirectRouteImport } from './routes/redirect'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as FormRouteImport } from './routes/form'
import { Route as DeferredRouteImport } from './routes/deferred'
import { Route as PathlessLayoutRouteImport } from './routes/_pathlessLayout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users.index'
import { Route as PostsIndexRouteImport } from './routes/posts.index'
import { Route as UsersUserIdRouteImport } from './routes/users.$userId'
import { Route as PostsPostIdRouteImport } from './routes/posts.$postId'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as ApiSubmissionsRouteImport } from './routes/api/submissions'
import { Route as ApiGlobalSettingsRouteImport } from './routes/api/global-settings'
import { Route as ApiFormSubmissionRouteImport } from './routes/api/form-submission'
import { Route as ApiFormSettingsRouteImport } from './routes/api/form-settings'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminLookupRouteImport } from './routes/admin.lookup'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminFormsRouteImport } from './routes/admin.forms'
import { Route as AdminCreateRouteImport } from './routes/admin.create'
import { Route as PathlessLayoutNestedLayoutRouteImport } from './routes/_pathlessLayout/_nested-layout'
import { Route as PostsPostIdDeepRouteImport } from './routes/posts_.$postId.deep'
import { Route as ApiUsersUserIdRouteImport } from './routes/api/users.$userId'
import { Route as ApiAdminToggleOverwriteRouteImport } from './routes/api/admin/toggle-overwrite'
import { Route as ApiAdminToggleExpiryRouteImport } from './routes/api/admin/toggle-expiry'
import { Route as ApiAdminSubmissionsByUserRouteImport } from './routes/api/admin/submissions-by-user'
import { Route as ApiAdminRemoveFormRouteImport } from './routes/api/admin/remove-form'
import { Route as ApiAdminGetAllFormsRouteImport } from './routes/api/admin/get-all-forms'
import { Route as ApiAdminEmailCsvReportRouteImport } from './routes/api/admin/email-csv-report'
import { Route as ApiAdminCreateFormRouteImport } from './routes/api/admin/create-form'
import { Route as PathlessLayoutNestedLayoutRouteBRouteImport } from './routes/_pathlessLayout/_nested-layout/route-b'
import { Route as PathlessLayoutNestedLayoutRouteARouteImport } from './routes/_pathlessLayout/_nested-layout/route-a'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const RedirectRoute = RedirectRouteImport.update({
  id: '/redirect',
  path: '/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const FormRoute = FormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => rootRouteImport,
} as any)
const DeferredRoute = DeferredRouteImport.update({
  id: '/deferred',
  path: '/deferred',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutRoute = PathlessLayoutRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersRoute,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostsRoute,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => UsersRoute,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => PostsRoute,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubmissionsRoute = ApiSubmissionsRouteImport.update({
  id: '/api/submissions',
  path: '/api/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGlobalSettingsRoute = ApiGlobalSettingsRouteImport.update({
  id: '/api/global-settings',
  path: '/api/global-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFormSubmissionRoute = ApiFormSubmissionRouteImport.update({
  id: '/api/form-submission',
  path: '/api/form-submission',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFormSettingsRoute = ApiFormSettingsRouteImport.update({
  id: '/api/form-settings',
  path: '/api/form-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLookupRoute = AdminLookupRouteImport.update({
  id: '/admin/lookup',
  path: '/admin/lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFormsRoute = AdminFormsRouteImport.update({
  id: '/admin/forms',
  path: '/admin/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCreateRoute = AdminCreateRouteImport.update({
  id: '/admin/create',
  path: '/admin/create',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutNestedLayoutRoute =
  PathlessLayoutNestedLayoutRouteImport.update({
    id: '/_nested-layout',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)
const PostsPostIdDeepRoute = PostsPostIdDeepRouteImport.update({
  id: '/posts_/$postId/deep',
  path: '/posts/$postId/deep',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersUserIdRoute = ApiUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => ApiUsersRoute,
} as any)
const ApiAdminToggleOverwriteRoute = ApiAdminToggleOverwriteRouteImport.update({
  id: '/api/admin/toggle-overwrite',
  path: '/api/admin/toggle-overwrite',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminToggleExpiryRoute = ApiAdminToggleExpiryRouteImport.update({
  id: '/api/admin/toggle-expiry',
  path: '/api/admin/toggle-expiry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSubmissionsByUserRoute =
  ApiAdminSubmissionsByUserRouteImport.update({
    id: '/api/admin/submissions-by-user',
    path: '/api/admin/submissions-by-user',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminRemoveFormRoute = ApiAdminRemoveFormRouteImport.update({
  id: '/api/admin/remove-form',
  path: '/api/admin/remove-form',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminGetAllFormsRoute = ApiAdminGetAllFormsRouteImport.update({
  id: '/api/admin/get-all-forms',
  path: '/api/admin/get-all-forms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminEmailCsvReportRoute = ApiAdminEmailCsvReportRouteImport.update({
  id: '/api/admin/email-csv-report',
  path: '/api/admin/email-csv-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCreateFormRoute = ApiAdminCreateFormRouteImport.update({
  id: '/api/admin/create-form',
  path: '/api/admin/create-form',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutNestedLayoutRouteBRoute =
  PathlessLayoutNestedLayoutRouteBRouteImport.update({
    id: '/route-b',
    path: '/route-b',
    getParentRoute: () => PathlessLayoutNestedLayoutRoute,
  } as any)
const PathlessLayoutNestedLayoutRouteARoute =
  PathlessLayoutNestedLayoutRouteARouteImport.update({
    id: '/route-a',
    path: '/route-a',
    getParentRoute: () => PathlessLayoutNestedLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deferred': typeof DeferredRoute
  '/form': typeof FormRoute
  '/posts': typeof PostsRouteWithChildren
  '/redirect': typeof RedirectRoute
  '/users': typeof UsersRouteWithChildren
  '/admin/create': typeof AdminCreateRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/lookup': typeof AdminLookupRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/form-settings': typeof ApiFormSettingsRoute
  '/api/form-submission': typeof ApiFormSubmissionRoute
  '/api/global-settings': typeof ApiGlobalSettingsRoute
  '/api/submissions': typeof ApiSubmissionsRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/posts/$postId': typeof PostsPostIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/posts/': typeof PostsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/api/admin/create-form': typeof ApiAdminCreateFormRoute
  '/api/admin/email-csv-report': typeof ApiAdminEmailCsvReportRoute
  '/api/admin/get-all-forms': typeof ApiAdminGetAllFormsRoute
  '/api/admin/remove-form': typeof ApiAdminRemoveFormRoute
  '/api/admin/submissions-by-user': typeof ApiAdminSubmissionsByUserRoute
  '/api/admin/toggle-expiry': typeof ApiAdminToggleExpiryRoute
  '/api/admin/toggle-overwrite': typeof ApiAdminToggleOverwriteRoute
  '/api/users/$userId': typeof ApiUsersUserIdRoute
  '/posts/$postId/deep': typeof PostsPostIdDeepRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deferred': typeof DeferredRoute
  '/form': typeof FormRoute
  '/redirect': typeof RedirectRoute
  '/admin/create': typeof AdminCreateRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/lookup': typeof AdminLookupRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/form-settings': typeof ApiFormSettingsRoute
  '/api/form-submission': typeof ApiFormSubmissionRoute
  '/api/global-settings': typeof ApiGlobalSettingsRoute
  '/api/submissions': typeof ApiSubmissionsRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/posts/$postId': typeof PostsPostIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/posts': typeof PostsIndexRoute
  '/users': typeof UsersIndexRoute
  '/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/api/admin/create-form': typeof ApiAdminCreateFormRoute
  '/api/admin/email-csv-report': typeof ApiAdminEmailCsvReportRoute
  '/api/admin/get-all-forms': typeof ApiAdminGetAllFormsRoute
  '/api/admin/remove-form': typeof ApiAdminRemoveFormRoute
  '/api/admin/submissions-by-user': typeof ApiAdminSubmissionsByUserRoute
  '/api/admin/toggle-expiry': typeof ApiAdminToggleExpiryRoute
  '/api/admin/toggle-overwrite': typeof ApiAdminToggleOverwriteRoute
  '/api/users/$userId': typeof ApiUsersUserIdRoute
  '/posts/$postId/deep': typeof PostsPostIdDeepRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_pathlessLayout': typeof PathlessLayoutRouteWithChildren
  '/deferred': typeof DeferredRoute
  '/form': typeof FormRoute
  '/posts': typeof PostsRouteWithChildren
  '/redirect': typeof RedirectRoute
  '/users': typeof UsersRouteWithChildren
  '/_pathlessLayout/_nested-layout': typeof PathlessLayoutNestedLayoutRouteWithChildren
  '/admin/create': typeof AdminCreateRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/lookup': typeof AdminLookupRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/form-settings': typeof ApiFormSettingsRoute
  '/api/form-submission': typeof ApiFormSubmissionRoute
  '/api/global-settings': typeof ApiGlobalSettingsRoute
  '/api/submissions': typeof ApiSubmissionsRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/posts/$postId': typeof PostsPostIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/posts/': typeof PostsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/_pathlessLayout/_nested-layout/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/_pathlessLayout/_nested-layout/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/api/admin/create-form': typeof ApiAdminCreateFormRoute
  '/api/admin/email-csv-report': typeof ApiAdminEmailCsvReportRoute
  '/api/admin/get-all-forms': typeof ApiAdminGetAllFormsRoute
  '/api/admin/remove-form': typeof ApiAdminRemoveFormRoute
  '/api/admin/submissions-by-user': typeof ApiAdminSubmissionsByUserRoute
  '/api/admin/toggle-expiry': typeof ApiAdminToggleExpiryRoute
  '/api/admin/toggle-overwrite': typeof ApiAdminToggleOverwriteRoute
  '/api/users/$userId': typeof ApiUsersUserIdRoute
  '/posts_/$postId/deep': typeof PostsPostIdDeepRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/deferred'
    | '/form'
    | '/posts'
    | '/redirect'
    | '/users'
    | '/admin/create'
    | '/admin/forms'
    | '/admin/login'
    | '/admin/lookup'
    | '/admin/settings'
    | '/api/form-settings'
    | '/api/form-submission'
    | '/api/global-settings'
    | '/api/submissions'
    | '/api/users'
    | '/posts/$postId'
    | '/users/$userId'
    | '/posts/'
    | '/users/'
    | '/route-a'
    | '/route-b'
    | '/api/admin/create-form'
    | '/api/admin/email-csv-report'
    | '/api/admin/get-all-forms'
    | '/api/admin/remove-form'
    | '/api/admin/submissions-by-user'
    | '/api/admin/toggle-expiry'
    | '/api/admin/toggle-overwrite'
    | '/api/users/$userId'
    | '/posts/$postId/deep'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/deferred'
    | '/form'
    | '/redirect'
    | '/admin/create'
    | '/admin/forms'
    | '/admin/login'
    | '/admin/lookup'
    | '/admin/settings'
    | '/api/form-settings'
    | '/api/form-submission'
    | '/api/global-settings'
    | '/api/submissions'
    | '/api/users'
    | '/posts/$postId'
    | '/users/$userId'
    | '/posts'
    | '/users'
    | '/route-a'
    | '/route-b'
    | '/api/admin/create-form'
    | '/api/admin/email-csv-report'
    | '/api/admin/get-all-forms'
    | '/api/admin/remove-form'
    | '/api/admin/submissions-by-user'
    | '/api/admin/toggle-expiry'
    | '/api/admin/toggle-overwrite'
    | '/api/users/$userId'
    | '/posts/$postId/deep'
  id:
    | '__root__'
    | '/'
    | '/_pathlessLayout'
    | '/deferred'
    | '/form'
    | '/posts'
    | '/redirect'
    | '/users'
    | '/_pathlessLayout/_nested-layout'
    | '/admin/create'
    | '/admin/forms'
    | '/admin/login'
    | '/admin/lookup'
    | '/admin/settings'
    | '/api/form-settings'
    | '/api/form-submission'
    | '/api/global-settings'
    | '/api/submissions'
    | '/api/users'
    | '/posts/$postId'
    | '/users/$userId'
    | '/posts/'
    | '/users/'
    | '/_pathlessLayout/_nested-layout/route-a'
    | '/_pathlessLayout/_nested-layout/route-b'
    | '/api/admin/create-form'
    | '/api/admin/email-csv-report'
    | '/api/admin/get-all-forms'
    | '/api/admin/remove-form'
    | '/api/admin/submissions-by-user'
    | '/api/admin/toggle-expiry'
    | '/api/admin/toggle-overwrite'
    | '/api/users/$userId'
    | '/posts_/$postId/deep'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PathlessLayoutRoute: typeof PathlessLayoutRouteWithChildren
  DeferredRoute: typeof DeferredRoute
  FormRoute: typeof FormRoute
  PostsRoute: typeof PostsRouteWithChildren
  RedirectRoute: typeof RedirectRoute
  UsersRoute: typeof UsersRouteWithChildren
  AdminCreateRoute: typeof AdminCreateRoute
  AdminFormsRoute: typeof AdminFormsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminLookupRoute: typeof AdminLookupRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  ApiFormSettingsRoute: typeof ApiFormSettingsRoute
  ApiFormSubmissionRoute: typeof ApiFormSubmissionRoute
  ApiGlobalSettingsRoute: typeof ApiGlobalSettingsRoute
  ApiSubmissionsRoute: typeof ApiSubmissionsRoute
  ApiUsersRoute: typeof ApiUsersRouteWithChildren
  ApiAdminCreateFormRoute: typeof ApiAdminCreateFormRoute
  ApiAdminEmailCsvReportRoute: typeof ApiAdminEmailCsvReportRoute
  ApiAdminGetAllFormsRoute: typeof ApiAdminGetAllFormsRoute
  ApiAdminRemoveFormRoute: typeof ApiAdminRemoveFormRoute
  ApiAdminSubmissionsByUserRoute: typeof ApiAdminSubmissionsByUserRoute
  ApiAdminToggleExpiryRoute: typeof ApiAdminToggleExpiryRoute
  ApiAdminToggleOverwriteRoute: typeof ApiAdminToggleOverwriteRoute
  PostsPostIdDeepRoute: typeof PostsPostIdDeepRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redirect': {
      id: '/redirect'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof RedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form': {
      id: '/form'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof FormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deferred': {
      id: '/deferred'
      path: '/deferred'
      fullPath: '/deferred'
      preLoaderRoute: typeof DeferredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PathlessLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof UsersRoute
    }
    '/posts/': {
      id: '/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof PostsRoute
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof UsersRoute
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof PostsRoute
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/submissions': {
      id: '/api/submissions'
      path: '/api/submissions'
      fullPath: '/api/submissions'
      preLoaderRoute: typeof ApiSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/global-settings': {
      id: '/api/global-settings'
      path: '/api/global-settings'
      fullPath: '/api/global-settings'
      preLoaderRoute: typeof ApiGlobalSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/form-submission': {
      id: '/api/form-submission'
      path: '/api/form-submission'
      fullPath: '/api/form-submission'
      preLoaderRoute: typeof ApiFormSubmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/form-settings': {
      id: '/api/form-settings'
      path: '/api/form-settings'
      fullPath: '/api/form-settings'
      preLoaderRoute: typeof ApiFormSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/lookup': {
      id: '/admin/lookup'
      path: '/admin/lookup'
      fullPath: '/admin/lookup'
      preLoaderRoute: typeof AdminLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/forms': {
      id: '/admin/forms'
      path: '/admin/forms'
      fullPath: '/admin/forms'
      preLoaderRoute: typeof AdminFormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/create': {
      id: '/admin/create'
      path: '/admin/create'
      fullPath: '/admin/create'
      preLoaderRoute: typeof AdminCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/_nested-layout': {
      id: '/_pathlessLayout/_nested-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/posts_/$postId/deep': {
      id: '/posts_/$postId/deep'
      path: '/posts/$postId/deep'
      fullPath: '/posts/$postId/deep'
      preLoaderRoute: typeof PostsPostIdDeepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/$userId': {
      id: '/api/users/$userId'
      path: '/$userId'
      fullPath: '/api/users/$userId'
      preLoaderRoute: typeof ApiUsersUserIdRouteImport
      parentRoute: typeof ApiUsersRoute
    }
    '/api/admin/toggle-overwrite': {
      id: '/api/admin/toggle-overwrite'
      path: '/api/admin/toggle-overwrite'
      fullPath: '/api/admin/toggle-overwrite'
      preLoaderRoute: typeof ApiAdminToggleOverwriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/toggle-expiry': {
      id: '/api/admin/toggle-expiry'
      path: '/api/admin/toggle-expiry'
      fullPath: '/api/admin/toggle-expiry'
      preLoaderRoute: typeof ApiAdminToggleExpiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/submissions-by-user': {
      id: '/api/admin/submissions-by-user'
      path: '/api/admin/submissions-by-user'
      fullPath: '/api/admin/submissions-by-user'
      preLoaderRoute: typeof ApiAdminSubmissionsByUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/remove-form': {
      id: '/api/admin/remove-form'
      path: '/api/admin/remove-form'
      fullPath: '/api/admin/remove-form'
      preLoaderRoute: typeof ApiAdminRemoveFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/get-all-forms': {
      id: '/api/admin/get-all-forms'
      path: '/api/admin/get-all-forms'
      fullPath: '/api/admin/get-all-forms'
      preLoaderRoute: typeof ApiAdminGetAllFormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/email-csv-report': {
      id: '/api/admin/email-csv-report'
      path: '/api/admin/email-csv-report'
      fullPath: '/api/admin/email-csv-report'
      preLoaderRoute: typeof ApiAdminEmailCsvReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/create-form': {
      id: '/api/admin/create-form'
      path: '/api/admin/create-form'
      fullPath: '/api/admin/create-form'
      preLoaderRoute: typeof ApiAdminCreateFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/_nested-layout/route-b': {
      id: '/_pathlessLayout/_nested-layout/route-b'
      path: '/route-b'
      fullPath: '/route-b'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteBRouteImport
      parentRoute: typeof PathlessLayoutNestedLayoutRoute
    }
    '/_pathlessLayout/_nested-layout/route-a': {
      id: '/_pathlessLayout/_nested-layout/route-a'
      path: '/route-a'
      fullPath: '/route-a'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteARouteImport
      parentRoute: typeof PathlessLayoutNestedLayoutRoute
    }
  }
}

interface PathlessLayoutNestedLayoutRouteChildren {
  PathlessLayoutNestedLayoutRouteARoute: typeof PathlessLayoutNestedLayoutRouteARoute
  PathlessLayoutNestedLayoutRouteBRoute: typeof PathlessLayoutNestedLayoutRouteBRoute
}

const PathlessLayoutNestedLayoutRouteChildren: PathlessLayoutNestedLayoutRouteChildren =
  {
    PathlessLayoutNestedLayoutRouteARoute:
      PathlessLayoutNestedLayoutRouteARoute,
    PathlessLayoutNestedLayoutRouteBRoute:
      PathlessLayoutNestedLayoutRouteBRoute,
  }

const PathlessLayoutNestedLayoutRouteWithChildren =
  PathlessLayoutNestedLayoutRoute._addFileChildren(
    PathlessLayoutNestedLayoutRouteChildren,
  )

interface PathlessLayoutRouteChildren {
  PathlessLayoutNestedLayoutRoute: typeof PathlessLayoutNestedLayoutRouteWithChildren
}

const PathlessLayoutRouteChildren: PathlessLayoutRouteChildren = {
  PathlessLayoutNestedLayoutRoute: PathlessLayoutNestedLayoutRouteWithChildren,
}

const PathlessLayoutRouteWithChildren = PathlessLayoutRoute._addFileChildren(
  PathlessLayoutRouteChildren,
)

interface PostsRouteChildren {
  PostsPostIdRoute: typeof PostsPostIdRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

const PostsRouteChildren: PostsRouteChildren = {
  PostsPostIdRoute: PostsPostIdRoute,
  PostsIndexRoute: PostsIndexRoute,
}

const PostsRouteWithChildren = PostsRoute._addFileChildren(PostsRouteChildren)

interface UsersRouteChildren {
  UsersUserIdRoute: typeof UsersUserIdRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

const UsersRouteChildren: UsersRouteChildren = {
  UsersUserIdRoute: UsersUserIdRoute,
  UsersIndexRoute: UsersIndexRoute,
}

const UsersRouteWithChildren = UsersRoute._addFileChildren(UsersRouteChildren)

interface ApiUsersRouteChildren {
  ApiUsersUserIdRoute: typeof ApiUsersUserIdRoute
}

const ApiUsersRouteChildren: ApiUsersRouteChildren = {
  ApiUsersUserIdRoute: ApiUsersUserIdRoute,
}

const ApiUsersRouteWithChildren = ApiUsersRoute._addFileChildren(
  ApiUsersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PathlessLayoutRoute: PathlessLayoutRouteWithChildren,
  DeferredRoute: DeferredRoute,
  FormRoute: FormRoute,
  PostsRoute: PostsRouteWithChildren,
  RedirectRoute: RedirectRoute,
  UsersRoute: UsersRouteWithChildren,
  AdminCreateRoute: AdminCreateRoute,
  AdminFormsRoute: AdminFormsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminLookupRoute: AdminLookupRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  ApiFormSettingsRoute: ApiFormSettingsRoute,
  ApiFormSubmissionRoute: ApiFormSubmissionRoute,
  ApiGlobalSettingsRoute: ApiGlobalSettingsRoute,
  ApiSubmissionsRoute: ApiSubmissionsRoute,
  ApiUsersRoute: ApiUsersRouteWithChildren,
  ApiAdminCreateFormRoute: ApiAdminCreateFormRoute,
  ApiAdminEmailCsvReportRoute: ApiAdminEmailCsvReportRoute,
  ApiAdminGetAllFormsRoute: ApiAdminGetAllFormsRoute,
  ApiAdminRemoveFormRoute: ApiAdminRemoveFormRoute,
  ApiAdminSubmissionsByUserRoute: ApiAdminSubmissionsByUserRoute,
  ApiAdminToggleExpiryRoute: ApiAdminToggleExpiryRoute,
  ApiAdminToggleOverwriteRoute: ApiAdminToggleOverwriteRoute,
  PostsPostIdDeepRoute: PostsPostIdDeepRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
