/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedirectRouteImport } from './routes/redirect'
import { Route as LookupRouteImport } from './routes/lookup'
import { Route as PathlessLayoutRouteImport } from './routes/_pathlessLayout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FormFormIdRouteImport } from './routes/form.$formId'
import { Route as ApiSubmissionsByUserRouteImport } from './routes/api/submissions-by-user'
import { Route as ApiSubmissionsRouteImport } from './routes/api/submissions'
import { Route as ApiGlobalSettingsRouteImport } from './routes/api/global-settings'
import { Route as ApiFormSettingsRouteImport } from './routes/api/form-settings'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminFormsRouteImport } from './routes/admin.forms'
import { Route as AdminCreateRouteImport } from './routes/admin.create'
import { Route as PathlessLayoutNestedLayoutRouteImport } from './routes/_pathlessLayout/_nested-layout'
import { Route as ApiAdminToggleOverwriteRouteImport } from './routes/api/admin/toggle-overwrite'
import { Route as ApiAdminToggleExpiryRouteImport } from './routes/api/admin/toggle-expiry'
import { Route as ApiAdminRemoveFormRouteImport } from './routes/api/admin/remove-form'
import { Route as ApiAdminRefreshAuthRouteImport } from './routes/api/admin/refresh-auth'
import { Route as ApiAdminLogoutRouteImport } from './routes/api/admin/logout'
import { Route as ApiAdminLoginRouteImport } from './routes/api/admin/login'
import { Route as ApiAdminGetAllFormsRouteImport } from './routes/api/admin/get-all-forms'
import { Route as ApiAdminFormSubmissionsRouteImport } from './routes/api/admin/form-submissions'
import { Route as ApiAdminEmailCsvReportRouteImport } from './routes/api/admin/email-csv-report'
import { Route as ApiAdminCreateFormRouteImport } from './routes/api/admin/create-form'
import { Route as PathlessLayoutNestedLayoutRouteBRouteImport } from './routes/_pathlessLayout/_nested-layout/route-b'
import { Route as PathlessLayoutNestedLayoutRouteARouteImport } from './routes/_pathlessLayout/_nested-layout/route-a'

const RedirectRoute = RedirectRouteImport.update({
  id: '/redirect',
  path: '/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const LookupRoute = LookupRouteImport.update({
  id: '/lookup',
  path: '/lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutRoute = PathlessLayoutRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormFormIdRoute = FormFormIdRouteImport.update({
  id: '/form/$formId',
  path: '/form/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubmissionsByUserRoute = ApiSubmissionsByUserRouteImport.update({
  id: '/api/submissions-by-user',
  path: '/api/submissions-by-user',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubmissionsRoute = ApiSubmissionsRouteImport.update({
  id: '/api/submissions',
  path: '/api/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGlobalSettingsRoute = ApiGlobalSettingsRouteImport.update({
  id: '/api/global-settings',
  path: '/api/global-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFormSettingsRoute = ApiFormSettingsRouteImport.update({
  id: '/api/form-settings',
  path: '/api/form-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFormsRoute = AdminFormsRouteImport.update({
  id: '/admin/forms',
  path: '/admin/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCreateRoute = AdminCreateRouteImport.update({
  id: '/admin/create',
  path: '/admin/create',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutNestedLayoutRoute =
  PathlessLayoutNestedLayoutRouteImport.update({
    id: '/_nested-layout',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)
const ApiAdminToggleOverwriteRoute = ApiAdminToggleOverwriteRouteImport.update({
  id: '/api/admin/toggle-overwrite',
  path: '/api/admin/toggle-overwrite',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminToggleExpiryRoute = ApiAdminToggleExpiryRouteImport.update({
  id: '/api/admin/toggle-expiry',
  path: '/api/admin/toggle-expiry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRemoveFormRoute = ApiAdminRemoveFormRouteImport.update({
  id: '/api/admin/remove-form',
  path: '/api/admin/remove-form',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRefreshAuthRoute = ApiAdminRefreshAuthRouteImport.update({
  id: '/api/admin/refresh-auth',
  path: '/api/admin/refresh-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLogoutRoute = ApiAdminLogoutRouteImport.update({
  id: '/api/admin/logout',
  path: '/api/admin/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminGetAllFormsRoute = ApiAdminGetAllFormsRouteImport.update({
  id: '/api/admin/get-all-forms',
  path: '/api/admin/get-all-forms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminFormSubmissionsRoute = ApiAdminFormSubmissionsRouteImport.update({
  id: '/api/admin/form-submissions',
  path: '/api/admin/form-submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminEmailCsvReportRoute = ApiAdminEmailCsvReportRouteImport.update({
  id: '/api/admin/email-csv-report',
  path: '/api/admin/email-csv-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCreateFormRoute = ApiAdminCreateFormRouteImport.update({
  id: '/api/admin/create-form',
  path: '/api/admin/create-form',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutNestedLayoutRouteBRoute =
  PathlessLayoutNestedLayoutRouteBRouteImport.update({
    id: '/route-b',
    path: '/route-b',
    getParentRoute: () => PathlessLayoutNestedLayoutRoute,
  } as any)
const PathlessLayoutNestedLayoutRouteARoute =
  PathlessLayoutNestedLayoutRouteARouteImport.update({
    id: '/route-a',
    path: '/route-a',
    getParentRoute: () => PathlessLayoutNestedLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lookup': typeof LookupRoute
  '/redirect': typeof RedirectRoute
  '/admin/create': typeof AdminCreateRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/form-settings': typeof ApiFormSettingsRoute
  '/api/global-settings': typeof ApiGlobalSettingsRoute
  '/api/submissions': typeof ApiSubmissionsRoute
  '/api/submissions-by-user': typeof ApiSubmissionsByUserRoute
  '/form/$formId': typeof FormFormIdRoute
  '/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/api/admin/create-form': typeof ApiAdminCreateFormRoute
  '/api/admin/email-csv-report': typeof ApiAdminEmailCsvReportRoute
  '/api/admin/form-submissions': typeof ApiAdminFormSubmissionsRoute
  '/api/admin/get-all-forms': typeof ApiAdminGetAllFormsRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/refresh-auth': typeof ApiAdminRefreshAuthRoute
  '/api/admin/remove-form': typeof ApiAdminRemoveFormRoute
  '/api/admin/toggle-expiry': typeof ApiAdminToggleExpiryRoute
  '/api/admin/toggle-overwrite': typeof ApiAdminToggleOverwriteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lookup': typeof LookupRoute
  '/redirect': typeof RedirectRoute
  '/admin/create': typeof AdminCreateRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/form-settings': typeof ApiFormSettingsRoute
  '/api/global-settings': typeof ApiGlobalSettingsRoute
  '/api/submissions': typeof ApiSubmissionsRoute
  '/api/submissions-by-user': typeof ApiSubmissionsByUserRoute
  '/form/$formId': typeof FormFormIdRoute
  '/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/api/admin/create-form': typeof ApiAdminCreateFormRoute
  '/api/admin/email-csv-report': typeof ApiAdminEmailCsvReportRoute
  '/api/admin/form-submissions': typeof ApiAdminFormSubmissionsRoute
  '/api/admin/get-all-forms': typeof ApiAdminGetAllFormsRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/refresh-auth': typeof ApiAdminRefreshAuthRoute
  '/api/admin/remove-form': typeof ApiAdminRemoveFormRoute
  '/api/admin/toggle-expiry': typeof ApiAdminToggleExpiryRoute
  '/api/admin/toggle-overwrite': typeof ApiAdminToggleOverwriteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_pathlessLayout': typeof PathlessLayoutRouteWithChildren
  '/lookup': typeof LookupRoute
  '/redirect': typeof RedirectRoute
  '/_pathlessLayout/_nested-layout': typeof PathlessLayoutNestedLayoutRouteWithChildren
  '/admin/create': typeof AdminCreateRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/form-settings': typeof ApiFormSettingsRoute
  '/api/global-settings': typeof ApiGlobalSettingsRoute
  '/api/submissions': typeof ApiSubmissionsRoute
  '/api/submissions-by-user': typeof ApiSubmissionsByUserRoute
  '/form/$formId': typeof FormFormIdRoute
  '/_pathlessLayout/_nested-layout/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/_pathlessLayout/_nested-layout/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/api/admin/create-form': typeof ApiAdminCreateFormRoute
  '/api/admin/email-csv-report': typeof ApiAdminEmailCsvReportRoute
  '/api/admin/form-submissions': typeof ApiAdminFormSubmissionsRoute
  '/api/admin/get-all-forms': typeof ApiAdminGetAllFormsRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/refresh-auth': typeof ApiAdminRefreshAuthRoute
  '/api/admin/remove-form': typeof ApiAdminRemoveFormRoute
  '/api/admin/toggle-expiry': typeof ApiAdminToggleExpiryRoute
  '/api/admin/toggle-overwrite': typeof ApiAdminToggleOverwriteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lookup'
    | '/redirect'
    | '/admin/create'
    | '/admin/forms'
    | '/admin/login'
    | '/admin/settings'
    | '/api/form-settings'
    | '/api/global-settings'
    | '/api/submissions'
    | '/api/submissions-by-user'
    | '/form/$formId'
    | '/route-a'
    | '/route-b'
    | '/api/admin/create-form'
    | '/api/admin/email-csv-report'
    | '/api/admin/form-submissions'
    | '/api/admin/get-all-forms'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/refresh-auth'
    | '/api/admin/remove-form'
    | '/api/admin/toggle-expiry'
    | '/api/admin/toggle-overwrite'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/lookup'
    | '/redirect'
    | '/admin/create'
    | '/admin/forms'
    | '/admin/login'
    | '/admin/settings'
    | '/api/form-settings'
    | '/api/global-settings'
    | '/api/submissions'
    | '/api/submissions-by-user'
    | '/form/$formId'
    | '/route-a'
    | '/route-b'
    | '/api/admin/create-form'
    | '/api/admin/email-csv-report'
    | '/api/admin/form-submissions'
    | '/api/admin/get-all-forms'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/refresh-auth'
    | '/api/admin/remove-form'
    | '/api/admin/toggle-expiry'
    | '/api/admin/toggle-overwrite'
  id:
    | '__root__'
    | '/'
    | '/_pathlessLayout'
    | '/lookup'
    | '/redirect'
    | '/_pathlessLayout/_nested-layout'
    | '/admin/create'
    | '/admin/forms'
    | '/admin/login'
    | '/admin/settings'
    | '/api/form-settings'
    | '/api/global-settings'
    | '/api/submissions'
    | '/api/submissions-by-user'
    | '/form/$formId'
    | '/_pathlessLayout/_nested-layout/route-a'
    | '/_pathlessLayout/_nested-layout/route-b'
    | '/api/admin/create-form'
    | '/api/admin/email-csv-report'
    | '/api/admin/form-submissions'
    | '/api/admin/get-all-forms'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/refresh-auth'
    | '/api/admin/remove-form'
    | '/api/admin/toggle-expiry'
    | '/api/admin/toggle-overwrite'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PathlessLayoutRoute: typeof PathlessLayoutRouteWithChildren
  LookupRoute: typeof LookupRoute
  RedirectRoute: typeof RedirectRoute
  AdminCreateRoute: typeof AdminCreateRoute
  AdminFormsRoute: typeof AdminFormsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  ApiFormSettingsRoute: typeof ApiFormSettingsRoute
  ApiGlobalSettingsRoute: typeof ApiGlobalSettingsRoute
  ApiSubmissionsRoute: typeof ApiSubmissionsRoute
  ApiSubmissionsByUserRoute: typeof ApiSubmissionsByUserRoute
  FormFormIdRoute: typeof FormFormIdRoute
  ApiAdminCreateFormRoute: typeof ApiAdminCreateFormRoute
  ApiAdminEmailCsvReportRoute: typeof ApiAdminEmailCsvReportRoute
  ApiAdminFormSubmissionsRoute: typeof ApiAdminFormSubmissionsRoute
  ApiAdminGetAllFormsRoute: typeof ApiAdminGetAllFormsRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminLogoutRoute: typeof ApiAdminLogoutRoute
  ApiAdminRefreshAuthRoute: typeof ApiAdminRefreshAuthRoute
  ApiAdminRemoveFormRoute: typeof ApiAdminRemoveFormRoute
  ApiAdminToggleExpiryRoute: typeof ApiAdminToggleExpiryRoute
  ApiAdminToggleOverwriteRoute: typeof ApiAdminToggleOverwriteRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/redirect': {
      id: '/redirect'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof RedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookup': {
      id: '/lookup'
      path: '/lookup'
      fullPath: '/lookup'
      preLoaderRoute: typeof LookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PathlessLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form/$formId': {
      id: '/form/$formId'
      path: '/form/$formId'
      fullPath: '/form/$formId'
      preLoaderRoute: typeof FormFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/submissions-by-user': {
      id: '/api/submissions-by-user'
      path: '/api/submissions-by-user'
      fullPath: '/api/submissions-by-user'
      preLoaderRoute: typeof ApiSubmissionsByUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/submissions': {
      id: '/api/submissions'
      path: '/api/submissions'
      fullPath: '/api/submissions'
      preLoaderRoute: typeof ApiSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/global-settings': {
      id: '/api/global-settings'
      path: '/api/global-settings'
      fullPath: '/api/global-settings'
      preLoaderRoute: typeof ApiGlobalSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/form-settings': {
      id: '/api/form-settings'
      path: '/api/form-settings'
      fullPath: '/api/form-settings'
      preLoaderRoute: typeof ApiFormSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/forms': {
      id: '/admin/forms'
      path: '/admin/forms'
      fullPath: '/admin/forms'
      preLoaderRoute: typeof AdminFormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/create': {
      id: '/admin/create'
      path: '/admin/create'
      fullPath: '/admin/create'
      preLoaderRoute: typeof AdminCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/_nested-layout': {
      id: '/_pathlessLayout/_nested-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/api/admin/toggle-overwrite': {
      id: '/api/admin/toggle-overwrite'
      path: '/api/admin/toggle-overwrite'
      fullPath: '/api/admin/toggle-overwrite'
      preLoaderRoute: typeof ApiAdminToggleOverwriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/toggle-expiry': {
      id: '/api/admin/toggle-expiry'
      path: '/api/admin/toggle-expiry'
      fullPath: '/api/admin/toggle-expiry'
      preLoaderRoute: typeof ApiAdminToggleExpiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/remove-form': {
      id: '/api/admin/remove-form'
      path: '/api/admin/remove-form'
      fullPath: '/api/admin/remove-form'
      preLoaderRoute: typeof ApiAdminRemoveFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/refresh-auth': {
      id: '/api/admin/refresh-auth'
      path: '/api/admin/refresh-auth'
      fullPath: '/api/admin/refresh-auth'
      preLoaderRoute: typeof ApiAdminRefreshAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/logout': {
      id: '/api/admin/logout'
      path: '/api/admin/logout'
      fullPath: '/api/admin/logout'
      preLoaderRoute: typeof ApiAdminLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/get-all-forms': {
      id: '/api/admin/get-all-forms'
      path: '/api/admin/get-all-forms'
      fullPath: '/api/admin/get-all-forms'
      preLoaderRoute: typeof ApiAdminGetAllFormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/form-submissions': {
      id: '/api/admin/form-submissions'
      path: '/api/admin/form-submissions'
      fullPath: '/api/admin/form-submissions'
      preLoaderRoute: typeof ApiAdminFormSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/email-csv-report': {
      id: '/api/admin/email-csv-report'
      path: '/api/admin/email-csv-report'
      fullPath: '/api/admin/email-csv-report'
      preLoaderRoute: typeof ApiAdminEmailCsvReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/create-form': {
      id: '/api/admin/create-form'
      path: '/api/admin/create-form'
      fullPath: '/api/admin/create-form'
      preLoaderRoute: typeof ApiAdminCreateFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/_nested-layout/route-b': {
      id: '/_pathlessLayout/_nested-layout/route-b'
      path: '/route-b'
      fullPath: '/route-b'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteBRouteImport
      parentRoute: typeof PathlessLayoutNestedLayoutRoute
    }
    '/_pathlessLayout/_nested-layout/route-a': {
      id: '/_pathlessLayout/_nested-layout/route-a'
      path: '/route-a'
      fullPath: '/route-a'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteARouteImport
      parentRoute: typeof PathlessLayoutNestedLayoutRoute
    }
  }
}

interface PathlessLayoutNestedLayoutRouteChildren {
  PathlessLayoutNestedLayoutRouteARoute: typeof PathlessLayoutNestedLayoutRouteARoute
  PathlessLayoutNestedLayoutRouteBRoute: typeof PathlessLayoutNestedLayoutRouteBRoute
}

const PathlessLayoutNestedLayoutRouteChildren: PathlessLayoutNestedLayoutRouteChildren =
  {
    PathlessLayoutNestedLayoutRouteARoute:
      PathlessLayoutNestedLayoutRouteARoute,
    PathlessLayoutNestedLayoutRouteBRoute:
      PathlessLayoutNestedLayoutRouteBRoute,
  }

const PathlessLayoutNestedLayoutRouteWithChildren =
  PathlessLayoutNestedLayoutRoute._addFileChildren(
    PathlessLayoutNestedLayoutRouteChildren,
  )

interface PathlessLayoutRouteChildren {
  PathlessLayoutNestedLayoutRoute: typeof PathlessLayoutNestedLayoutRouteWithChildren
}

const PathlessLayoutRouteChildren: PathlessLayoutRouteChildren = {
  PathlessLayoutNestedLayoutRoute: PathlessLayoutNestedLayoutRouteWithChildren,
}

const PathlessLayoutRouteWithChildren = PathlessLayoutRoute._addFileChildren(
  PathlessLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PathlessLayoutRoute: PathlessLayoutRouteWithChildren,
  LookupRoute: LookupRoute,
  RedirectRoute: RedirectRoute,
  AdminCreateRoute: AdminCreateRoute,
  AdminFormsRoute: AdminFormsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  ApiFormSettingsRoute: ApiFormSettingsRoute,
  ApiGlobalSettingsRoute: ApiGlobalSettingsRoute,
  ApiSubmissionsRoute: ApiSubmissionsRoute,
  ApiSubmissionsByUserRoute: ApiSubmissionsByUserRoute,
  FormFormIdRoute: FormFormIdRoute,
  ApiAdminCreateFormRoute: ApiAdminCreateFormRoute,
  ApiAdminEmailCsvReportRoute: ApiAdminEmailCsvReportRoute,
  ApiAdminFormSubmissionsRoute: ApiAdminFormSubmissionsRoute,
  ApiAdminGetAllFormsRoute: ApiAdminGetAllFormsRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminLogoutRoute: ApiAdminLogoutRoute,
  ApiAdminRefreshAuthRoute: ApiAdminRefreshAuthRoute,
  ApiAdminRemoveFormRoute: ApiAdminRemoveFormRoute,
  ApiAdminToggleExpiryRoute: ApiAdminToggleExpiryRoute,
  ApiAdminToggleOverwriteRoute: ApiAdminToggleOverwriteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
